services:
  web:
    build: .
    image: yuki_img:latest
    container_name: yuki_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
      - static_volume:/app/static/uploads

volumes:
  static_volume:
